config/routes.rb
Whitehorse::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/our_work"

  get "static_pages/what_we_do"

  get "static_pages/contact"

  resources :users

   root :to => 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :ph_no
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def our_work
  end

  def what_we_do
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-inverse">
  <div class="navbar-inner">
   <div class="row-fluid">
      <div class="span12"> 
        <div class="span4 invent">
          <b>By Prashant Dixit</b>
        </div>
        <div class="span4 site_links"><a href="http://railstutorial.org/">White Horse</a></div>
        <div class="links_footer span4">
          <ul>
            <li><%= link_to "About",   '#' %></li>
            <li><%= link_to "Contact", '#' %></li>
            <li><a href="#">News</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>
   
<style>
.navbar-inverse .navbar-inner{
  background-image:none;
  color:#CEC6C6;
}
.navbar-inner .links_footer ul li, .navbar-inner .site_links, .invent b{ 
    color: #AEAEAE;
    display: block;
    font-size: 16px;
    font-weight: 300;
    line-height: 60px;
    text-transform: uppercase;
  }
</style>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse" id="mydiv" >
  <div class="navbar-inner">
    <div class="container">
      <div class="row-fluid box">
        <div class="span12"> 
          <div class="span4">
            <h2> <%= link_to "White Horse", '#', id: "logo" %></h2>
          </div>
          <div class="span2"%></div>
          <div class="span4">
            <nav>
              <ul class="nav pull-right diplay">
                <li class="jumper"><%= link_to "Contact",'#contact'  %></li>
                <li class="jumper"><%= link_to "Our Work",'#our_works' %></li>
                <li class="jumper"><%= link_to "Home", '#home' %></li>
                <li class="jumper"><%= link_to "What We Do", '#what_we_do' %></li>
              </ul>	
            </nav>
          </div>  
    </div> 
  </div>
</header>
<script>
  $(window).scroll(function (event) {
    var top = $('.box').offset().top;
    var y = $(this).scrollTop();
    if (y >= 730 ) { $('.box').addClass('fixed');}
    else { $('.box').removeClass('fixed');}
  }); 
</script>
<style>
.boxes {
     position: absolute;
}
.navbar .nav.pull-right{
  padding-left:10px;
}
.fixed {
    position: fixed;
    top: 0px;
    background:#414C48;
    width: 110%;
    margin-left: -22px;

}
.navbar-inverse .navbar-inner{
   background: #414C48;
}
.diplay{
  margin-left: 10px;
}
</style>

app/views/layouts/_image.html.erb
<div class="location_of_images" style="margin-top:-60px;">
  <%= image_tag("motivational.png") %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whitehorse</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/image" %>
<%= render "layouts/header" %>
<%= yield %>
<%= render "layouts/footer" %>
</body>
</html>

app/views/static_pages/_contact.html.erb
<div id="contact" class="jumper" style="height:400px;">
	<h3> Our Teams</h3>
	<hr>
    <div class="row-fluid">
    	<div class="span12" style="background: #CCC;">
    	    <div class="span1"></div> 
			<div class="span3">
     	      <%= image_tag("aa1.jpg",  :class => "circular") %>
     	      <h3>Abhishek Kumar</h3>
     	      <p> Software Developer </p>
			</div>
			 <div class="span1"></div>
			<div class="span3">
		        <%= image_tag("pp1.jpg", :class => "circular") %>
		         <h3>Prashant Dixit</h3>
     	      <p> Software Developer </p> 
			</div>
			<div class="span1"></div>
			<div class="span3">
		        <!--%= image_tag("image3.jpg", :class => "circular") %-->
		         <!--h3>Prashant Dixit</h3-->
     	      <p>  </p> 
			</div>
		</div>	
    </div>		
</div>
<hr>
<style>
.circular {
	width: 180px;
	height: 180px;
	border-radius: 50px;
	-webkit-border-radius: 50px;
	-moz-border-radius: 50px;
	}
</style>

app/views/static_pages/_home.html.erb
<div id="home" class="jumper" style="height:350px;">
	<div>
		<h3>What We Do</h3>
		<p>We work with technology startups throughout the product lifecycle, right from conception till launch and thereafter.</p>
	</div>
  	<hr>
	<div class="row-fluid" style="background: #CCC;">
    	<div class="span12"  >
    	    <div class="span1"></div> 
			<div class="span3">
     	      <%= image_tag("Koala.jpg",  :class => "circular") %>
     	      <h3>Design</h3>
     	      <p> Architecture, User Interaction, User Experience,</p><p> Database Schema, Mockups, Scalability, Performance </p>
			</div>
			 <div class="span1"></div>
			<div class="span3">
		        <%= image_tag("Lighthouse.jpg", :class => "circular") %>
		         <h3>Develop</h3>
     	     Ruby, Rails, Scala, Akka, Python, SQL, NoSQL, CSS3, HTML5, Backbone, jQuery, Node.js, TDD, Cucumber, Rspec, Selenium, Yslow, iOS, Android 
			</div>
			<div class="span1"></div>
			<div class="span3">
		        <%= image_tag("Penguins.jpg", :class => "circular") %>
		         <h3>Deploy</h3>
     	      <p> AWS, Heroku, Capistrano, CDN, Auto Scaling, Load Balancing, Memcached, CI, Jenkins, Chef</p> 
			</div>
		</div>	
    </div>	

</div>
<hr>

app/views/static_pages/_our_work.html.erb
<div id="our_works" class="jumper">
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :ph_no %><br />
    <%= f.text_field :ph_no %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div style="background-color: #E8E3DE;">
	<%= render "static_pages/contact" %>
	<%= render "static_pages/home" %>
	<%= render "static_pages/what_we_do" %> 
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Ph no:</b>
  <%= @user.ph_no %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>